name: Deploy Fitness SaaS API

on:
  push:
    branches:
      - staging

jobs:
  deploy_staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/fitness-saas && cd apps/fitness-saas
            
            if [ -d ".git" ]; then
              git stash
              git pull origin staging
            else
              git clone -b staging https://github.com/ShalOps/gym-sass-backend.git .
            fi
            
            npm install --force
            
            # Run Prisma migrations
            npx prisma generate
            npx prisma migrate deploy
            
            # Build the application
            npm run build

            pid=$(pm2 pid "fitness-saas" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading fitness-saas"
              pm2 reload "fitness-saas"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "fitness-saas" -- start -- -p 64389
              pm2 startup
              pm2 save
            fi
